import io
import re
import zipfile
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, Field


class GenerateRequest(BaseModel):
    language: str
    framework: str
    template: str = "Dashboard"
    app_name: str = Field(min_length=1, max_length=80)
    version: str = "1.0.0"
    theme: str = "Dark Prism"
    features: list[str] = Field(default_factory=list)
    license_header: str | None = None
    initialize_git: bool = False


@dataclass
class GeneratedProject:
    filename: str
    content: bytes


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip()).strip("-").lower()
    return slug or "generated-app"


def class_name(value: str) -> str:
    name = "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", value) if part)
    return name if name and not name[0].isdigit() else f"App{name}"


def header(request: GenerateRequest, prefix: str) -> str:
    if not request.license_header:
        return ""
    return "\n".join(f"{prefix} {line}" for line in request.license_header.splitlines()) + "\n\n"


class ProjectGenerator:
    def generate_zip(self, request: GenerateRequest) -> GeneratedProject:
        files = self.generate_files(request)
        archive = io.BytesIO()
        root = slugify(request.app_name)
        with zipfile.ZipFile(archive, mode="w", compression=zipfile.ZIP_DEFLATED) as zip_file:
            for relative_path, content in files.items():
                zip_file.writestr(f"{root}/{relative_path}", content)
        archive.seek(0)
        return GeneratedProject(filename=f"{root}.zip", content=archive.read())

    def generate_files(self, request: GenerateRequest) -> dict[str, str]:
        if request.language == "python":
            return self._python(request)
        if request.language == "cpp":
            return self._cpp(request)
        if request.language == "csharp":
            return self._csharp(request)
        if request.language == "java":
            return self._java(request)
        raise ValueError("Unsupported language.")

    def _readme(self, request: GenerateRequest, commands: list[str]) -> str:
        return f"""# {request.app_name}

Generated by PrismDashboard Web App Builder.

## Stack
- Language: {request.language}
- Framework: {request.framework}
- Template: {request.template}
- Theme: {request.theme}
- Version: {request.version}

## Commands
{chr(10).join(f"- `{command}`" for command in commands)}
"""

    def _python(self, request: GenerateRequest) -> dict[str, str]:
        dependency_map = {
            "Tkinter": "",
            "CustomTkinter": "customtkinter>=5.2.2\n",
            "PyQt6": "PyQt6>=6.7.0\n",
            "Dear PyGui": "dearpygui>=1.11.1\n",
            "Streamlit": "streamlit>=1.36.0\n",
            "Flet": "flet>=0.23.0\n",
        }
        deps = dependency_map.get(request.framework, "customtkinter>=5.2.2\n") + "pyinstaller>=6.8.0\nnuitka>=2.3.0\n"
        main = f'''{header(request, "#")}import customtkinter as ctk


class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        ctk.set_appearance_mode("dark")
        self.title("{request.app_name}")
        self.geometry("1280x800")
        self.grid_columnconfigure(1, weight=1)
        sidebar = ctk.CTkFrame(self, width=260, corner_radius=0)
        sidebar.grid(row=0, column=0, sticky="nsew")
        ctk.CTkLabel(sidebar, text="{request.app_name}", font=("Segoe UI", 24, "bold")).pack(padx=24, pady=24, anchor="w")
        content = ctk.CTkFrame(self, corner_radius=12)
        content.grid(row=0, column=1, sticky="nsew", padx=24, pady=24)
        ctk.CTkLabel(content, text="{request.template}", font=("Segoe UI", 32, "bold")).pack(anchor="w", padx=24, pady=(24, 8))
        ctk.CTkLabel(content, text="Generated with {request.framework} by PrismDashboard.").pack(anchor="w", padx=24)
        ctk.CTkButton(content, text="Run Action", command=lambda: self.status.configure(text="Action complete")).pack(anchor="w", padx=24, pady=24)
        self.status = ctk.CTkLabel(content, text="Ready")
        self.status.pack(anchor="w", padx=24)


if __name__ == "__main__":
    App().mainloop()
'''
        return {
            "main.py": main,
            "requirements.txt": deps,
            "pyproject.toml": f'[project]\nname = "{slugify(request.app_name)}"\nversion = "{request.version}"\nrequires-python = ">=3.11"\n',
            "setup.py": f'from setuptools import setup\nsetup(name="{slugify(request.app_name)}", version="{request.version}", py_modules=["main"])\n',
            "scripts/setup_venv.bat": "python -m venv .venv\r\ncall .venv\\Scripts\\activate\r\npython -m pip install --upgrade pip\r\npip install -r requirements.txt\r\n",
            "scripts/build_pyinstaller.bat": "call .venv\\Scripts\\activate\r\npyinstaller --noconfirm --onefile --windowed main.py\r\n",
            "scripts/build_nuitka.bat": "call .venv\\Scripts\\activate\r\npython -m nuitka --standalone --onefile --windows-console-mode=disable main.py\r\n",
            "README.md": self._readme(request, ["scripts\\setup_venv.bat", "python main.py", "scripts\\build_pyinstaller.bat"]),
        }

    def _cpp(self, request: GenerateRequest) -> dict[str, str]:
        cname = class_name(request.app_name)
        main = f'''{header(request, "//")}#include <iostream>

int main()
{{
    std::cout << "{request.app_name} generated by PrismDashboard.\\n";
    std::cout << "Framework: {request.framework}\\n";
    return 0;
}}
'''
        return {
            "src/main.cpp": main,
            "CMakeLists.txt": f"cmake_minimum_required(VERSION 3.24)\nproject({cname} LANGUAGES CXX)\nset(CMAKE_CXX_STANDARD 20)\nadd_executable({cname} src/main.cpp)\n",
            f"{cname}.vcxproj": self._vcxproj(cname),
            f"{cname}.sln": "Microsoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\nGlobal\nEndGlobal\n",
            "build.bat": "cmake -S . -B build -A x64\r\ncmake --build build --config Release\r\n",
            "build.sh": "#!/usr/bin/env bash\nset -euo pipefail\ncmake -S . -B build -DCMAKE_BUILD_TYPE=Release\ncmake --build build\n",
            "README.md": self._readme(request, ["cmake -S . -B build -A x64", "cmake --build build --config Release"]),
        }

    def _vcxproj(self, cname: str) -> str:
        return f'''<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64"><Configuration>Debug</Configuration><Platform>x64</Platform></ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64"><Configuration>Release</Configuration><Platform>x64</Platform></ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals"><VCProjectVersion>17.0</VCProjectVersion><Keyword>Win32Proj</Keyword><RootNamespace>{cname}</RootNamespace><WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion></PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration"><ConfigurationType>Application</ConfigurationType><PlatformToolset>v143</PlatformToolset><CharacterSet>Unicode</CharacterSet></PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ItemDefinitionGroup><ClCompile><LanguageStandard>stdcpp20</LanguageStandard></ClCompile><Link><SubSystem>Console</SubSystem></Link></ItemDefinitionGroup>
  <ItemGroup><ClCompile Include="src\\main.cpp" /></ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
</Project>
'''

    def _csharp(self, request: GenerateRequest) -> dict[str, str]:
        cname = class_name(request.app_name)
        return {
            f"{cname}.sln": "Microsoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\nGlobal\nEndGlobal\n",
            f"{cname}.csproj": '<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable></PropertyGroup></Project>\n',
            "App.xaml.cs": f'{header(request, "//")}using System.Windows;\nnamespace {cname};\npublic partial class App : Application {{ [System.STAThread] public static void Main() => new App().Run(new MainWindow()); }}\n',
            "MainWindow.xaml.cs": f'using System.Windows;\nnamespace {cname};\npublic sealed class MainWindow : Window {{ public MainWindow() {{ Title = "{request.app_name}"; Width = 1280; Height = 800; }} }}\n',
            "ViewModels/MainViewModel.cs": f'namespace {cname}.ViewModels;\npublic sealed class MainViewModel {{ public string Title => "{request.app_name}"; }}\n',
            "build.ps1": "dotnet restore\ndotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true\n",
            "README.md": self._readme(request, ["dotnet restore", "dotnet run", "dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true"]),
        }

    def _java(self, request: GenerateRequest) -> dict[str, str]:
        slug = slugify(request.app_name).replace("-", ".")
        return {
            "src/main/java/app/Main.java": f'{header(request, "//")}package app;\n\npublic final class Main {{ public static void main(String[] args) {{ System.out.println("{request.app_name} generated by PrismDashboard."); }} }}\n',
            "src/main/java/module-info.java": "module generated.app { exports app; }\n",
            "pom.xml": f"<project><modelVersion>4.0.0</modelVersion><groupId>app.generated</groupId><artifactId>{slugify(request.app_name)}</artifactId><version>{request.version}</version><properties><maven.compiler.release>21</maven.compiler.release></properties></project>\n",
            "build.gradle": "plugins { id 'application' }\nrepositories { mavenCentral() }\njava { toolchain { languageVersion = JavaLanguageVersion.of(21) } }\napplication { mainClass = 'app.Main' }\n",
            "build.bat": "mvn clean package\r\n",
            "README.md": self._readme(request, ["mvn clean package", "gradle run", "java -cp target/classes app.Main"]),
        }
