// Purpose: Project generator backend and optional Dear ImGui surface for PrismDashboard.
// Dependencies: C++20 filesystem/string utilities; Dear ImGui is optional at compile time.
// Integration notes: Call RenderImGui() from the future PrismDashboard ImGui frame loop.
#include "AppBuilder.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <fstream>
#include <sstream>
#include <stdexcept>

#if __has_include("imgui.h")
#include "imgui.h"
#define PRISM_DASHBOARD_HAS_IMGUI 1
#else
#define PRISM_DASHBOARD_HAS_IMGUI 0
#endif

namespace {

std::string ReplaceAll(std::string value, const std::string& from, const std::string& to)
{
    size_t position = 0;
    while ((position = value.find(from, position)) != std::string::npos) {
        value.replace(position, from.length(), to);
        position += to.length();
    }
    return value;
}

std::string JoinCommands(const std::vector<BuildCommand>& commands)
{
    std::ostringstream output;
    for (const BuildCommand& command : commands) {
        output << "- " << command.label << ": `" << command.command << "`\n";
    }
    return output.str();
}

std::string CommonReadme(const AppBuilderConfig& config, const std::vector<BuildCommand>& commands)
{
    std::ostringstream readme;
    readme << "# " << config.appName << "\n\n";
    readme << "Generated by PrismDashboard App Builder.\n\n";
    readme << "## Project\n";
    readme << "- Version: " << config.version << "\n";
    readme << "- Framework: " << config.framework << "\n";
    readme << "- Theme: " << config.theme << "\n\n";
    readme << "## Commands\n" << JoinCommands(commands) << "\n";
    readme << "## Notes\n";
    readme << "The generated files are complete starter applications with install, run, and packaging scripts.\n";
    return readme.str();
}

std::string PythonMain(const AppBuilderConfig& config)
{
    const std::string title = config.appName;
    if (config.framework == "Tkinter") {
        return R"PY(import tkinter as tk
from tkinter import ttk, messagebox


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("{{APP_NAME}}")
        self.geometry("1280x800")
        self.configure(bg="#10131a")
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TFrame", background="#10131a")
        style.configure("Card.TFrame", background="#171b24")
        style.configure("TLabel", background="#10131a", foreground="#eef2ff", font=("Segoe UI", 11))
        style.configure("Title.TLabel", background="#10131a", foreground="#ffffff", font=("Segoe UI", 22, "bold"))
        style.configure("Accent.TButton", font=("Segoe UI", 11, "bold"), padding=10)
        self._build()

    def _build(self):
        root = ttk.Frame(self, padding=24)
        root.pack(fill="both", expand=True)
        ttk.Label(root, text="{{APP_NAME}}", style="Title.TLabel").pack(anchor="w")
        ttk.Label(root, text="Production desktop starter generated by PrismDashboard.").pack(anchor="w", pady=(8, 24))
        card = ttk.Frame(root, style="Card.TFrame", padding=20)
        card.pack(fill="x")
        ttk.Label(card, text="Dashboard").grid(row=0, column=0, sticky="w")
        ttk.Button(card, text="Run Action", style="Accent.TButton", command=self._action).grid(row=1, column=0, sticky="w", pady=(16, 0))

    def _action(self):
        messagebox.showinfo("{{APP_NAME}}", "Application action completed.")


if __name__ == "__main__":
    App().mainloop()
)PY";
    }

    if (config.framework == "PyQt6") {
        return R"PY(import sys
from PyQt6.QtWidgets import QApplication, QLabel, QMainWindow, QPushButton, QVBoxLayout, QWidget


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("{{APP_NAME}}")
        self.resize(1280, 800)
        container = QWidget()
        layout = QVBoxLayout(container)
        title = QLabel("{{APP_NAME}}")
        title.setObjectName("title")
        subtitle = QLabel("Modern PyQt6 desktop starter generated by PrismDashboard.")
        button = QPushButton("Run Action")
        button.clicked.connect(lambda: button.setText("Action Complete"))
        layout.addWidget(title)
        layout.addWidget(subtitle)
        layout.addWidget(button)
        layout.addStretch()
        self.setCentralWidget(container)
        self.setStyleSheet("""
            QWidget { background: #10131a; color: #eef2ff; font: 11pt 'Segoe UI'; }
            QLabel#title { font-size: 28px; font-weight: 700; color: white; }
            QPushButton { background: #2f6fed; border: 0; padding: 10px 16px; border-radius: 6px; color: white; font-weight: 700; }
            QPushButton:hover { background: #3f7df4; }
        """)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
)PY";
    }

    if (config.framework == "Dear PyGui") {
        return R"PY(import dearpygui.dearpygui as dpg


dpg.create_context()
dpg.create_viewport(title="{{APP_NAME}}", width=1280, height=800)
dpg.setup_dearpygui()

with dpg.window(label="{{APP_NAME}}", width=1260, height=760):
    dpg.add_text("{{APP_NAME}}")
    dpg.add_text("Dear PyGui desktop starter generated by PrismDashboard.")
    dpg.add_separator()
    dpg.add_button(label="Run Action", callback=lambda: dpg.set_value("status", "Action complete"))
    dpg.add_text("Ready", tag="status")

dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
)PY";
    }

    if (config.framework == "Streamlit") {
        return R"PY(import streamlit as st


st.set_page_config(page_title="{{APP_NAME}}", layout="wide")
st.title("{{APP_NAME}}")
st.caption("Streamlit app generated by PrismDashboard.")

left, right = st.columns([2, 1])
with left:
    st.subheader("Dashboard")
    st.line_chart({"active_users": [12, 20, 32, 48], "jobs": [4, 8, 7, 12]})
with right:
    st.metric("Build", "Ready")
    st.button("Run Action")
)PY";
    }

    if (config.framework == "Flet") {
        return R"PY(import flet as ft


def main(page: ft.Page):
    page.title = "{{APP_NAME}}"
    page.theme_mode = ft.ThemeMode.DARK
    page.window_width = 1280
    page.window_height = 800
    status = ft.Text("Ready")
    page.add(
        ft.Text("{{APP_NAME}}", size=32, weight=ft.FontWeight.BOLD),
        ft.Text("Flet desktop/web starter generated by PrismDashboard."),
        ft.ElevatedButton("Run Action", on_click=lambda _: setattr(status, "value", "Action complete") or page.update()),
        status,
    )


ft.app(target=main)
)PY";
    }

    return R"PY(import customtkinter as ctk


class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        ctk.set_appearance_mode("dark")
        ctk.set_default_color_theme("blue")
        self.title("{{APP_NAME}}")
        self.geometry("1280x800")
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=1)

        sidebar = ctk.CTkFrame(self, width=240, corner_radius=0)
        sidebar.grid(row=0, column=0, sticky="nsew")
        ctk.CTkLabel(sidebar, text="{{APP_NAME}}", font=("Segoe UI", 22, "bold")).pack(padx=20, pady=(24, 8), anchor="w")
        ctk.CTkButton(sidebar, text="Dashboard").pack(fill="x", padx=20, pady=8)
        ctk.CTkButton(sidebar, text="Settings").pack(fill="x", padx=20, pady=8)

        content = ctk.CTkFrame(self, corner_radius=8)
        content.grid(row=0, column=1, sticky="nsew", padx=20, pady=20)
        content.grid_columnconfigure(0, weight=1)
        ctk.CTkLabel(content, text="Dashboard", font=("Segoe UI", 28, "bold")).grid(row=0, column=0, sticky="w", padx=24, pady=(24, 8))
        ctk.CTkLabel(content, text="CustomTkinter starter generated by PrismDashboard.").grid(row=1, column=0, sticky="w", padx=24)
        ctk.CTkButton(content, text="Run Action", command=self._action).grid(row=2, column=0, sticky="w", padx=24, pady=24)
        self.status = ctk.CTkLabel(content, text="Ready")
        self.status.grid(row=3, column=0, sticky="w", padx=24)

    def _action(self):
        self.status.configure(text="Action complete")


if __name__ == "__main__":
    App().mainloop()
)PY";
}

std::string CppMain(const AppBuilderConfig& config)
{
    if (config.framework == "Qt6") {
        return R"CPP(#include <QApplication>
#include <QLabel>
#include <QMainWindow>
#include <QPushButton>
#include <QVBoxLayout>
#include <QWidget>

int main(int argc, char** argv)
{
    QApplication app(argc, argv);
    QMainWindow window;
    window.setWindowTitle("{{APP_NAME}}");
    window.resize(1280, 800);

    auto* content = new QWidget();
    auto* layout = new QVBoxLayout(content);
    auto* title = new QLabel("{{APP_NAME}}");
    title->setStyleSheet("font-size: 28px; font-weight: 700;");
    auto* subtitle = new QLabel("Qt6 starter generated by PrismDashboard.");
    auto* button = new QPushButton("Run Action");
    QObject::connect(button, &QPushButton::clicked, button, [button]() { button->setText("Action Complete"); });
    layout->addWidget(title);
    layout->addWidget(subtitle);
    layout->addWidget(button);
    layout->addStretch();

    window.setCentralWidget(content);
    window.setStyleSheet("QWidget { background: #10131a; color: #eef2ff; font-family: Segoe UI; } QPushButton { background: #2f6fed; color: white; padding: 10px 16px; border-radius: 6px; }");
    window.show();
    return app.exec();
}
)CPP";
    }

    if (config.framework == "wxWidgets") {
        return R"CPP(#include <wx/wx.h>

class MainFrame : public wxFrame {
public:
    MainFrame() : wxFrame(nullptr, wxID_ANY, "{{APP_NAME}}", wxDefaultPosition, wxSize(1280, 800))
    {
        auto* panel = new wxPanel(this);
        auto* sizer = new wxBoxSizer(wxVERTICAL);
        auto* title = new wxStaticText(panel, wxID_ANY, "{{APP_NAME}}");
        auto* button = new wxButton(panel, wxID_ANY, "Run Action");
        button->Bind(wxEVT_BUTTON, [button](wxCommandEvent&) { button->SetLabel("Action Complete"); });
        sizer->Add(title, 0, wxALL, 24);
        sizer->Add(new wxStaticText(panel, wxID_ANY, "wxWidgets starter generated by PrismDashboard."), 0, wxLEFT | wxRIGHT | wxBOTTOM, 24);
        sizer->Add(button, 0, wxLEFT | wxRIGHT, 24);
        panel->SetSizer(sizer);
    }
};

class App : public wxApp {
public:
    bool OnInit() override
    {
        auto* frame = new MainFrame();
        frame->Show();
        return true;
    }
};

wxIMPLEMENT_APP(App);
)CPP";
    }

    return R"CPP(#include <glad/gl.h>
#include <GLFW/glfw3.h>
#include <imgui.h>
#include <imgui_impl_glfw.h>
#include <imgui_impl_opengl3.h>

#include <stdexcept>

int main()
{
    if (!glfwInit()) {
        throw std::runtime_error("Failed to initialize GLFW.");
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    GLFWwindow* window = glfwCreateWindow(1280, 800, "{{APP_NAME}}", nullptr, nullptr);
    if (!window) {
        glfwTerminate();
        throw std::runtime_error("Failed to create window.");
    }

    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);
    if (!gladLoadGL(glfwGetProcAddress)) {
        throw std::runtime_error("Failed to load OpenGL.");
    }

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
    ImGui::StyleColorsDark();

    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init("#version 330");

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        ImGui::DockSpaceOverViewport(0, ImGui::GetMainViewport());
        ImGui::Begin("Dashboard");
        ImGui::TextUnformatted("{{APP_NAME}}");
        ImGui::Separator();
        ImGui::TextUnformatted("Dear ImGui + GLFW + OpenGL starter generated by PrismDashboard.");
        ImGui::Button("Run Action");
        ImGui::End();

        ImGui::Render();
        int width = 0;
        int height = 0;
        glfwGetFramebufferSize(window, &width, &height);
        glViewport(0, 0, width, height);
        glClearColor(0.06f, 0.07f, 0.10f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
            GLFWwindow* backup = glfwGetCurrentContext();
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();
            glfwMakeContextCurrent(backup);
        }

        glfwSwapBuffers(window);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
)CPP";
}

std::string CSharpProgram(const AppBuilderConfig& config)
{
    if (config.framework == "WPF") {
        return R"CS(using System.Windows;

namespace {{CLASS_NAME}};

public partial class App : Application
{
    [System.STAThread]
    public static void Main()
    {
        var app = new App();
        app.Run(new MainWindow());
    }
}
)CS";
    }

    if (config.framework == "WinForms") {
        return R"CS(using System;
using System.Drawing;
using System.Windows.Forms;

namespace {{CLASS_NAME}};

internal static class Program
{
    [STAThread]
    private static void Main()
    {
        ApplicationConfiguration.Initialize();
        Application.Run(new MainForm());
    }
}

public sealed class MainForm : Form
{
    public MainForm()
    {
        Text = "{{APP_NAME}}";
        Width = 1280;
        Height = 800;
        BackColor = Color.FromArgb(16, 19, 26);
        ForeColor = Color.White;
        var title = new Label { Text = "{{APP_NAME}}", Dock = DockStyle.Top, Height = 64, Font = new Font("Segoe UI", 24, FontStyle.Bold), Padding = new Padding(24, 16, 0, 0) };
        var button = new Button { Text = "Run Action", Width = 160, Height = 40, Left = 24, Top = 96 };
        button.Click += (_, _) => button.Text = "Action Complete";
        Controls.Add(button);
        Controls.Add(title);
    }
}
)CS";
    }

    return R"CS(using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Layout;
using Avalonia.Media;

namespace {{CLASS_NAME}};

public sealed class App : Application
{
    public override void OnFrameworkInitializationCompleted()
    {
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            desktop.MainWindow = new Window
            {
                Title = "{{APP_NAME}}",
                Width = 1280,
                Height = 800,
                Background = new SolidColorBrush(Color.Parse("#10131a")),
                Content = new StackPanel
                {
                    Margin = new Thickness(24),
                    Spacing = 16,
                    Children =
                    {
                        new TextBlock { Text = "{{APP_NAME}}", FontSize = 32, FontWeight = FontWeight.Bold, Foreground = Brushes.White },
                        new TextBlock { Text = "Avalonia starter generated by PrismDashboard.", Foreground = Brushes.White },
                        new Button { Content = "Run Action", HorizontalAlignment = HorizontalAlignment.Left }
                    }
                }
            };
        }
        base.OnFrameworkInitializationCompleted();
    }
}

internal static class Program
{
    [System.STAThread]
    public static void Main(string[] args)
    {
        BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);
    }

    public static AppBuilder BuildAvaloniaApp()
    {
        return AppBuilder.Configure<App>().UsePlatformDetect().LogToTrace();
    }
}
)CS";
}

std::string JavaMain(const AppBuilderConfig& config)
{
    if (config.framework == "Swing") {
        return R"JAVA(package app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public final class Main {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("{{APP_NAME}}");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1280, 800);
            JPanel panel = new JPanel(new BorderLayout(16, 16));
            panel.setBackground(new Color(16, 19, 26));
            JLabel title = new JLabel("{{APP_NAME}}");
            title.setForeground(Color.WHITE);
            title.setFont(new Font("Segoe UI", Font.BOLD, 28));
            JButton button = new JButton("Run Action");
            button.addActionListener(event -> button.setText("Action Complete"));
            panel.add(title, BorderLayout.NORTH);
            panel.add(button, BorderLayout.CENTER);
            frame.setContentPane(panel);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
)JAVA";
    }

    return R"JAVA(package app;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public final class Main extends Application {
    @Override
    public void start(Stage stage) {
        Label title = new Label("{{APP_NAME}}");
        title.setStyle("-fx-font-size: 32px; -fx-font-weight: 700;");
        Button button = new Button("Run Action");
        button.setOnAction(event -> button.setText("Action Complete"));
        VBox root = new VBox(16, title, new Label("JavaFX starter generated by PrismDashboard."), button);
        root.setStyle("-fx-padding: 24; -fx-background-color: #10131a; -fx-text-fill: white;");
        stage.setTitle("{{APP_NAME}}");
        stage.setScene(new Scene(root, 1280, 800));
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
)JAVA";
}

} // namespace

AppBuilder::AppBuilder() = default;

AppBuilderResult AppBuilder::GenerateProject(const AppBuilderConfig& config) const
{
    AppBuilderResult result;
    result.message = Validate(config);
    if (!result.message.empty()) {
        return result;
    }

    result.files = PreviewFiles(config);
    result.commands = BuildCommands(config);

    std::string error;
    if (!WriteProject(config, result.files, result.projectDirectory, error)) {
        result.message = error;
        return result;
    }

    if (config.features.initializeGit) {
        RunCommand("git init", result.projectDirectory);
    }

    if (config.features.createZipArchive && !CreateZip(result.projectDirectory, result.zipPath, error)) {
        result.message = "Project generated, but zip creation failed: " + error;
        return result;
    }

    result.success = true;
    result.message = "Project generated successfully.";
    return result;
}

std::vector<GeneratedFile> AppBuilder::PreviewFiles(const AppBuilderConfig& config) const
{
    switch (config.language) {
    case BuilderLanguage::Python:
        return GeneratePython(config);
    case BuilderLanguage::Cpp:
        return GenerateCpp(config);
    case BuilderLanguage::CSharp:
        return GenerateCSharp(config);
    case BuilderLanguage::Java:
        return GenerateJava(config);
    }
    return {};
}

std::vector<BuildCommand> AppBuilder::BuildCommands(const AppBuilderConfig& config) const
{
    switch (config.language) {
    case BuilderLanguage::Python:
        return PythonCommands(config);
    case BuilderLanguage::Cpp:
        return CppCommands(config);
    case BuilderLanguage::CSharp:
        return CSharpCommands(config);
    case BuilderLanguage::Java:
        return JavaCommands(config);
    }
    return {};
}

std::vector<std::string> AppBuilder::FrameworksFor(BuilderLanguage language) const
{
    switch (language) {
    case BuilderLanguage::Python:
        return { "Tkinter", "CustomTkinter", "PyQt6", "Dear PyGui", "Streamlit", "Flet" };
    case BuilderLanguage::Cpp:
        return { "Dear ImGui + GLFW + OpenGL", "Qt6", "wxWidgets" };
    case BuilderLanguage::CSharp:
        return { "WinForms", "WPF", "MAUI", "AvaloniaUI" };
    case BuilderLanguage::Java:
        return { "Swing", "JavaFX", "TornadoFX" };
    }
    return {};
}

std::string AppBuilder::Validate(const AppBuilderConfig& config) const
{
    if (ProjectSlug(config.appName).empty()) {
        return "App name must contain at least one letter or number.";
    }

    const std::vector<std::string> frameworks = FrameworksFor(config.language);
    if (std::find(frameworks.begin(), frameworks.end(), config.framework) == frameworks.end()) {
        return "Unsupported framework for selected language: " + config.framework;
    }

    if (config.outputDirectory.empty()) {
        return "Output directory is required.";
    }

    return {};
}

void AppBuilder::RenderImGui(AppBuilderConfig& config)
{
#if PRISM_DASHBOARD_HAS_IMGUI
    ImGui::Begin("App Builder");
    ImGui::TextUnformatted("PrismDashboard App Builder");
    ImGui::Separator();
    ImGui::InputText("App Name", config.appName.data(), config.appName.capacity() + 1);
    ImGui::InputText("Version", config.version.data(), config.version.capacity() + 1);
    ImGui::Checkbox("GUI Application", &config.features.guiApplication);
    ImGui::Checkbox("License Header", &config.features.includeLicenseHeader);
    ImGui::Checkbox("Initialize Git", &config.features.initializeGit);
    ImGui::Checkbox("Create Zip", &config.features.createZipArchive);
    ImGui::End();
#else
    (void)config;
#endif
}

std::vector<GeneratedFile> AppBuilder::GeneratePython(const AppBuilderConfig& config) const
{
    std::string requirement;
    if (config.framework == "CustomTkinter") requirement = "customtkinter>=5.2.2\n";
    if (config.framework == "PyQt6") requirement = "PyQt6>=6.7.0\n";
    if (config.framework == "Dear PyGui") requirement = "dearpygui>=1.11.1\n";
    if (config.framework == "Streamlit") requirement = "streamlit>=1.36.0\n";
    if (config.framework == "Flet") requirement = "flet>=0.23.0\n";
    requirement += "pyinstaller>=6.8.0\nnuitka>=2.3.0\n";

    std::string main = ReplaceAll(PythonMain(config), "{{APP_NAME}}", config.appName);
    main = LicensePrefix(config, "# ") + main;

    std::string pyproject = ReplaceAll(R"TOML([project]
name = "{{SLUG}}"
version = "{{VERSION}}"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
py-modules = ["main"]
)TOML", "{{SLUG}}", ProjectSlug(config.appName));
    pyproject = ReplaceAll(pyproject, "{{VERSION}}", config.version);

    std::string setup = ReplaceAll(R"PY(from setuptools import setup

setup(
    name="{{SLUG}}",
    version="{{VERSION}}",
    py_modules=["main"],
)
)PY", "{{SLUG}}", ProjectSlug(config.appName));
    setup = ReplaceAll(setup, "{{VERSION}}", config.version);

    return {
        { "main.py", main },
        { "requirements.txt", requirement },
        { "pyproject.toml", pyproject },
        { "setup.py", setup },
        { "scripts/setup_venv.bat", "python -m venv .venv\r\ncall .venv\\Scripts\\activate\r\npython -m pip install --upgrade pip\r\npip install -r requirements.txt\r\n" },
        { "scripts/build_pyinstaller.bat", "call .venv\\Scripts\\activate\r\npyinstaller --noconfirm --onefile --windowed main.py\r\n" },
        { "scripts/build_nuitka.bat", "call .venv\\Scripts\\activate\r\npython -m nuitka --standalone --onefile --windows-console-mode=disable main.py\r\n" },
        { "README.md", CommonReadme(config, PythonCommands(config)) }
    };
}

std::vector<GeneratedFile> AppBuilder::GenerateCpp(const AppBuilderConfig& config) const
{
    const std::string slug = ProjectSlug(config.appName);
    std::string main = ReplaceAll(CppMain(config), "{{APP_NAME}}", config.appName);
    main = LicensePrefix(config, "// ") + main;

    std::string cmake = R"CMAKE(cmake_minimum_required(VERSION 3.24)
project({{CLASS_NAME}} LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable({{CLASS_NAME}} src/main.cpp)
)CMAKE";
    if (config.framework == "Dear ImGui + GLFW + OpenGL") {
        cmake += R"CMAKE(
include(FetchContent)
FetchContent_Declare(glfw GIT_REPOSITORY https://github.com/glfw/glfw.git GIT_TAG 3.4)
FetchContent_Declare(imgui GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG docking)
FetchContent_Declare(glad GIT_REPOSITORY https://github.com/Dav1dde/glad.git GIT_TAG v2.0.8)
FetchContent_MakeAvailable(glfw imgui glad)
glad_add_library(glad_gl_core_33 STATIC API gl:core=3.3)
target_sources({{CLASS_NAME}} PRIVATE
    ${imgui_SOURCE_DIR}/imgui.cpp
    ${imgui_SOURCE_DIR}/imgui_draw.cpp
    ${imgui_SOURCE_DIR}/imgui_tables.cpp
    ${imgui_SOURCE_DIR}/imgui_widgets.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp
    ${imgui_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp
)
target_include_directories({{CLASS_NAME}} PRIVATE ${imgui_SOURCE_DIR} ${imgui_SOURCE_DIR}/backends)
target_link_libraries({{CLASS_NAME}} PRIVATE glfw glad_gl_core_33)
)CMAKE";
    } else if (config.framework == "Qt6") {
        cmake += "find_package(Qt6 REQUIRED COMPONENTS Widgets)\ntarget_link_libraries({{CLASS_NAME}} PRIVATE Qt6::Widgets)\n";
    } else {
        cmake += "find_package(wxWidgets REQUIRED COMPONENTS core base)\ninclude(${wxWidgets_USE_FILE})\ntarget_link_libraries({{CLASS_NAME}} PRIVATE ${wxWidgets_LIBRARIES})\n";
    }
    cmake = ReplaceAll(cmake, "{{CLASS_NAME}}", ClassName(config.appName));

    std::string vcxproj = ReplaceAll(R"XML(<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64"><Configuration>Debug</Configuration><Platform>x64</Platform></ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64"><Configuration>Release</Configuration><Platform>x64</Platform></ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals"><VCProjectVersion>17.0</VCProjectVersion><Keyword>Win32Proj</Keyword><RootNamespace>{{CLASS_NAME}}</RootNamespace><WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion></PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration"><ConfigurationType>Application</ConfigurationType><UseDebugLibraries>true</UseDebugLibraries><PlatformToolset>v143</PlatformToolset><CharacterSet>Unicode</CharacterSet></PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration"><ConfigurationType>Application</ConfigurationType><UseDebugLibraries>false</UseDebugLibraries><PlatformToolset>v143</PlatformToolset><WholeProgramOptimization>true</WholeProgramOptimization><CharacterSet>Unicode</CharacterSet></PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'"><ClCompile><LanguageStandard>stdcpp20</LanguageStandard><AdditionalIncludeDirectories>$(ProjectDir)src;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories></ClCompile><Link><SubSystem>Console</SubSystem></Link></ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'"><ClCompile><LanguageStandard>stdcpp20</LanguageStandard><AdditionalIncludeDirectories>$(ProjectDir)src;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories></ClCompile><Link><SubSystem>Console</SubSystem></Link></ItemDefinitionGroup>
  <ItemGroup><ClCompile Include="src\main.cpp" /></ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
)XML", "{{CLASS_NAME}}", ClassName(config.appName));

    std::string sln = ReplaceAll(R"SLN(Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "{{CLASS_NAME}}", "{{CLASS_NAME}}.vcxproj", "{11111111-1111-1111-1111-111111111111}"
EndProject
Global
EndGlobal
)SLN", "{{CLASS_NAME}}", ClassName(config.appName));

    return {
        { "src/main.cpp", main },
        { "CMakeLists.txt", cmake },
        { ClassName(config.appName) + ".vcxproj", vcxproj },
        { ClassName(config.appName) + ".sln", sln },
        { "build.bat", "cmake -S . -B build -A x64\r\ncmake --build build --config Release\r\n" },
        { "build.sh", "#!/usr/bin/env bash\nset -euo pipefail\ncmake -S . -B build -DCMAKE_BUILD_TYPE=Release\ncmake --build build\n" },
        { "README.md", CommonReadme(config, CppCommands(config)) }
    };
}

std::vector<GeneratedFile> AppBuilder::GenerateCSharp(const AppBuilderConfig& config) const
{
    const std::string className = ClassName(config.appName);
    std::string sdk = "Microsoft.NET.Sdk";
    std::string useWpf;
    std::string useWindowsForms;
    std::string packageRefs;
    if (config.framework == "WPF") {
        sdk = "Microsoft.NET.Sdk.WindowsDesktop";
        useWpf = "<UseWPF>true</UseWPF>";
    } else if (config.framework == "WinForms") {
        sdk = "Microsoft.NET.Sdk.WindowsDesktop";
        useWindowsForms = "<UseWindowsForms>true</UseWindowsForms>";
    } else if (config.framework == "AvaloniaUI") {
        packageRefs = "<PackageReference Include=\"Avalonia\" Version=\"11.1.0\" />\n    <PackageReference Include=\"Avalonia.Desktop\" Version=\"11.1.0\" />";
    } else {
        packageRefs = "<PackageReference Include=\"Microsoft.Maui.Controls\" Version=\"8.0.80\" />";
    }

    std::string csproj = ReplaceAll(R"XML(<Project Sdk="{{SDK}}">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    {{USE_WPF}}
    {{USE_WINFORMS}}
  </PropertyGroup>
  <ItemGroup>
    {{PACKAGE_REFS}}
  </ItemGroup>
</Project>
)XML", "{{SDK}}", sdk);
    csproj = ReplaceAll(csproj, "{{USE_WPF}}", useWpf);
    csproj = ReplaceAll(csproj, "{{USE_WINFORMS}}", useWindowsForms);
    csproj = ReplaceAll(csproj, "{{PACKAGE_REFS}}", packageRefs);

    std::string program = ReplaceAll(CSharpProgram(config), "{{APP_NAME}}", config.appName);
    program = ReplaceAll(program, "{{CLASS_NAME}}", className);
    program = LicensePrefix(config, "// ") + program;

    return {
        { className + ".sln", "Microsoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\nGlobal\nEndGlobal\n" },
        { className + ".csproj", csproj },
        { "Program.cs", program },
        { "ViewModels/MainViewModel.cs", "namespace " + className + ".ViewModels;\n\npublic sealed class MainViewModel\n{\n    public string Title => \"" + config.appName + "\";\n}\n" },
        { "build.ps1", "dotnet restore\n dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true\n" },
        { "README.md", CommonReadme(config, CSharpCommands(config)) }
    };
}

std::vector<GeneratedFile> AppBuilder::GenerateJava(const AppBuilderConfig& config) const
{
    const std::string slug = ProjectSlug(config.appName);
    std::string main = ReplaceAll(JavaMain(config), "{{APP_NAME}}", config.appName);
    main = LicensePrefix(config, "// ") + main;

    std::string pom = ReplaceAll(R"XML(<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>app.generated</groupId>
  <artifactId>{{SLUG}}</artifactId>
  <version>{{VERSION}}</version>
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    {{DEPENDENCIES}}
  </dependencies>
</project>
)XML", "{{SLUG}}", slug);
    pom = ReplaceAll(pom, "{{VERSION}}", config.version);
    const std::string javafxDep = "<dependency><groupId>org.openjfx</groupId><artifactId>javafx-controls</artifactId><version>22.0.1</version></dependency>";
    pom = ReplaceAll(pom, "{{DEPENDENCIES}}", config.framework == "Swing" ? "" : javafxDep);

    std::string gradle = R"GRADLE(plugins {
    id 'application'
}

repositories { mavenCentral() }

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

dependencies {
}

application { mainClass = 'app.Main' }
)GRADLE";
    if (config.framework != "Swing") {
        gradle = ReplaceAll(gradle, "dependencies {\n}", "dependencies {\n    implementation 'org.openjfx:javafx-controls:22.0.1'\n}");
    }

    return {
        { "src/main/java/app/Main.java", main },
        { "src/main/java/module-info.java", config.framework == "Swing" ? "module " + slug + " {\n    requires java.desktop;\n}\n" : "module " + slug + " {\n    requires javafx.controls;\n    exports app;\n}\n" },
        { "pom.xml", pom },
        { "build.gradle", gradle },
        { "build.bat", "mvn clean package\r\n" },
        { "README.md", CommonReadme(config, JavaCommands(config)) }
    };
}

std::vector<BuildCommand> AppBuilder::PythonCommands(const AppBuilderConfig& config) const
{
    std::vector<BuildCommand> commands = {
        { "Create venv", "scripts\\setup_venv.bat" },
        { "Run", config.framework == "Streamlit" ? "streamlit run main.py" : "python main.py" },
        { "PyInstaller exe", "scripts\\build_pyinstaller.bat" },
        { "Nuitka exe", "scripts\\build_nuitka.bat" }
    };
    return commands;
}

std::vector<BuildCommand> AppBuilder::CppCommands(const AppBuilderConfig&) const
{
    return {
        { "Configure", "cmake -S . -B build -A x64" },
        { "Build", "cmake --build build --config Release" },
        { "Run", "build\\Release\\GeneratedApp.exe" }
    };
}

std::vector<BuildCommand> AppBuilder::CSharpCommands(const AppBuilderConfig&) const
{
    return {
        { "Restore", "dotnet restore" },
        { "Run", "dotnet run" },
        { "Publish single exe", "dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true" }
    };
}

std::vector<BuildCommand> AppBuilder::JavaCommands(const AppBuilderConfig&) const
{
    return {
        { "Maven package", "mvn clean package" },
        { "Gradle run", "gradle run" },
        { "Run classes", "java -cp target/classes app.Main" }
    };
}

std::string AppBuilder::ProjectSlug(const std::string& appName) const
{
    std::string slug;
    bool previousDash = false;
    for (unsigned char character : appName) {
        if (std::isalnum(character)) {
            slug.push_back(static_cast<char>(std::tolower(character)));
            previousDash = false;
        } else if (!previousDash && !slug.empty()) {
            slug.push_back('-');
            previousDash = true;
        }
    }
    while (!slug.empty() && slug.back() == '-') {
        slug.pop_back();
    }
    return slug;
}

std::string AppBuilder::ClassName(const std::string& appName) const
{
    std::string name;
    bool capitalize = true;
    for (unsigned char character : appName) {
        if (std::isalnum(character)) {
            name.push_back(static_cast<char>(capitalize ? std::toupper(character) : character));
            capitalize = false;
        } else {
            capitalize = true;
        }
    }
    if (name.empty() || std::isdigit(static_cast<unsigned char>(name.front()))) {
        name.insert(name.begin(), 'A');
    }
    return name;
}

std::string AppBuilder::LicensePrefix(const AppBuilderConfig& config, const std::string& commentPrefix) const
{
    if (!config.features.includeLicenseHeader || config.licenseHeader.empty()) {
        return {};
    }

    std::ostringstream output;
    std::istringstream input(config.licenseHeader);
    std::string line;
    while (std::getline(input, line)) {
        output << commentPrefix << line << "\n";
    }
    output << "\n";
    return output.str();
}

bool AppBuilder::WriteProject(const AppBuilderConfig& config, const std::vector<GeneratedFile>& files, std::filesystem::path& projectDirectory, std::string& error) const
{
    projectDirectory = config.outputDirectory / ProjectSlug(config.appName);
    std::error_code code;
    std::filesystem::create_directories(projectDirectory, code);
    if (code) {
        error = code.message();
        return false;
    }

    for (const GeneratedFile& file : files) {
        const std::filesystem::path target = projectDirectory / file.relativePath;
        std::filesystem::create_directories(target.parent_path(), code);
        if (code) {
            error = code.message();
            return false;
        }

        std::ofstream stream(target, std::ios::binary);
        if (!stream) {
            error = "Unable to write " + target.string();
            return false;
        }
        stream << file.contents;
    }

    return true;
}

bool AppBuilder::CreateZip(const std::filesystem::path& projectDirectory, std::filesystem::path& zipPath, std::string& error) const
{
    zipPath = projectDirectory;
    zipPath += ".zip";
    const std::string command = "powershell -NoProfile -ExecutionPolicy Bypass -Command \"if (Test-Path '" + zipPath.string() + "') { Remove-Item '" + zipPath.string() + "' -Force }; Compress-Archive -Path '" + projectDirectory.string() + "\\*' -DestinationPath '" + zipPath.string() + "'\"";
    const int exitCode = std::system(command.c_str());
    if (exitCode != 0) {
        error = "Compress-Archive exited with code " + std::to_string(exitCode);
        return false;
    }
    return true;
}

bool AppBuilder::RunCommand(const std::string& command, const std::filesystem::path& workingDirectory) const
{
    const std::filesystem::path original = std::filesystem::current_path();
    std::error_code code;
    std::filesystem::current_path(workingDirectory, code);
    if (code) {
        return false;
    }
    const int exitCode = std::system(command.c_str());
    std::filesystem::current_path(original, code);
    return exitCode == 0;
}
